import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { moneyValue, validDueDate } from '@/services/transaction-accounting';
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value);
export function TransactionFinanceFields({ kind, total, subtotal, tax, mode, onMode, paid, onPaid, dueDate, onDueDate, method, onMethod }: {
  kind: 'sale' | 'purchase'; total: number; subtotal: number; tax: number; mode: 'full' | 'partial' | 'credit'; onMode: (value: 'full' | 'partial' | 'credit') => void; paid: string; onPaid: (value: string) => void; dueDate: string; onDueDate: (value: string) => void; method: string; onMethod: (value: string) => void;
}) {
  const payment = mode === 'full' ? total : mode === 'credit' ? 0 : Number(paid || 0);
  const invalid = mode === 'partial' && (!paid || !Number.isFinite(payment) || payment <= 0 || payment >= total);
  return <View style={styles.card}>
    <View style={styles.row}><Text style={styles.meta}>Subtotal · excluding GST</Text><Text style={styles.bold}>{money(subtotal)}</Text></View>
    <View style={styles.row}><Text style={styles.meta}>GST · configured item rates</Text><Text style={styles.bold}>{money(tax)}</Text></View>
    <View style={[styles.row, styles.totalRow]}><Text style={styles.meta}>Total amount</Text><Text style={styles.total}>{money(total)}</Text></View>
    <Text style={styles.title}>{kind === 'sale' ? 'Payment received' : 'Payment to supplier'}</Text>
    <View style={styles.chips}>{(['full', 'partial', 'credit'] as const).map((value) => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: mode === value }} onPress={() => onMode(value)} style={[styles.chip, mode === value && styles.selected]}><Text style={[styles.chipText, mode === value && styles.selectedText]}>{value === 'full' ? 'Fully paid' : value === 'partial' ? 'Partial' : 'Full credit'}</Text></Pressable>)}</View>
    {mode === 'partial' ? <><Text style={styles.meta}>{kind === 'sale' ? 'Amount received (₹)' : 'Amount paid (₹)'}</Text><TextInput accessibilityLabel="Initial payment amount" keyboardType="decimal-pad" value={paid} onChangeText={(value) => { if (/^\d{0,12}(?:\.\d{0,2})?$/.test(value)) onPaid(value); }} placeholder="0.00" style={styles.input} />{invalid ? <Text style={styles.error}>Enter an amount greater than zero and below the total.</Text> : null}</> : null}
    {mode !== 'credit' ? <><Text style={styles.meta}>Payment method</Text><View style={styles.chips}>{['CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER'].map((value) => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: method === value }} onPress={() => onMethod(value)} style={[styles.chip, method === value && styles.selected]}><Text style={[styles.chipText, method === value && styles.selectedText]}>{value.replaceAll('_', ' ')}</Text></Pressable>)}</View></> : null}
    <View style={styles.row}><Text style={styles.meta}>{kind === 'sale' ? 'Balance to collect' : 'Balance to pay'}</Text><Text style={styles.bold}>{money(Math.max(0, moneyValue(total - payment)))}</Text></View>
    {mode !== 'full' ? <><Text style={styles.meta}>Due date · optional</Text><TextInput accessibilityLabel="Payment due date YYYY-MM-DD" value={dueDate} onChangeText={onDueDate} maxLength={10} placeholder="YYYY-MM-DD" style={styles.input} />{!validDueDate(dueDate) ? <Text style={styles.error}>Enter a valid date in YYYY-MM-DD format.</Text> : null}</> : null}
    <Text style={styles.meta}>Payment entries are saved with this transaction. No money is transferred by the app.</Text>
  </View>;
}
const styles = StyleSheet.create({ card: { padding: 16, borderRadius: 15, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E0E6E2', gap: 12, marginVertical: 16 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, meta: { color: '#737B77', fontSize: 12, lineHeight: 18 }, bold: { color: '#24332A', fontWeight: '700', fontSize: 14 }, totalRow: { borderTopWidth: 1, borderTopColor: '#E0E6E2', paddingTop: 12 }, total: { color: '#176B50', fontSize: 24, fontWeight: '800' }, title: { color: '#24332A', fontSize: 15, fontWeight: '700', marginTop: 8 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { borderWidth: 1, borderColor: '#DFE5E1', paddingHorizontal: 12, paddingVertical: 12, borderRadius: 10 }, selected: { backgroundColor: '#176B50', borderColor: '#176B50' }, chipText: { color: '#68746E', fontSize: 12, fontWeight: '600' }, selectedText: { color: '#FFFFFF' }, input: { borderWidth: 1, borderColor: '#DFE5E1', minHeight: 48, borderRadius: 10, paddingHorizontal: 12, color: '#24332A' }, error: { color: '#A74737', fontSize: 12 } });
