import type { PaymentRecord } from '@/services/api';
import { paymentBalance, isOverdue } from '@/services/transaction-accounting';
import { useState } from 'react';
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { formatUnitLabel } from './invento-ui';

export type ReceiptData = {
  id: string; kind: 'sale' | 'purchase'; date: string; invoice?: string | null; contact: string; total?: string | number | null; paymentMethod?: string; note?: string | null;
  subtotal?: string | number; taxTotal?: string | number; amountPaid?: string | number | null; dueDate?: string | null; payments?: PaymentRecord[];
  items: { id: string; name: string; sku?: string; quantity: number; label: string; price?: number; stockAfter?: number; stockUnit?: string; gstRate?: string | number; taxAmount?: string | number; lineTotal?: string | number }[];
};
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(value);
export function TransactionReceipt({ data, onBack, onView, onNew, onRepeat, onPayment }: { data: ReceiptData; onBack: () => void; onView?: () => void; onNew: () => void; onRepeat?: () => void; onPayment?: () => void }) {
  const insets = useSafeAreaInsets();
  const [error, setError] = useState('');
  const title = data.kind === 'sale' ? 'Sale' : 'Purchase';
  const identifier = data.kind === 'sale' ? data.invoice || data.id : data.id;
  const balance = paymentBalance(data);
  const overdue = isOverdue(data);
  const total = data.total == null ? 'Restricted price' : money(Number(data.total));
  const share = async () => {
    try {
      await Share.share({ message: [`${title} receipt · ${identifier}`, new Date(data.date).toLocaleDateString('en-IN', { dateStyle: 'medium' }), `${data.kind === 'sale' ? 'Customer' : 'Supplier'}: ${data.contact}`, ...data.items.map((item) => `${item.name} · ${item.quantity} ${item.label}${item.price == null ? '' : ` × ${money(item.price)} = ${money(Number((item.quantity * item.price).toFixed(2)))}`}`), `Subtotal: ${data.subtotal == null ? 'Restricted' : money(Number(data.subtotal))}`, `GST: ${data.taxTotal == null ? 'Restricted' : money(Number(data.taxTotal))}`, `Total: ${total}`, ...(balance == null ? [] : [`Paid: ${money(Number(data.amountPaid))}`, `Balance: ${money(balance)}`]), ...(data.paymentMethod ? [`Payment method: ${data.paymentMethod.replaceAll('_', ' ')}`] : [])].join('\n') });
    } catch { setError('Could not share this receipt. Please try again.'); }
  };
  return <View style={[styles.screen, { paddingTop: insets.top }]}>
    <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Close receipt" onPress={onBack} style={styles.back}><Ionicons name="arrow-back" size={24} color="#24332A" /></Pressable><View><Text style={styles.title}>{title} receipt</Text><Text style={styles.meta}>Invento · {new Date(data.date).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</Text></View></View>
    <ScrollView contentContainerStyle={styles.content}>
      {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
      <View style={styles.success}><Ionicons name="checkmark-circle-outline" size={21} color="#176B50" /><View style={{ flex: 1 }}><Text style={styles.greenTitle}>Saved · {title} recorded</Text><Text style={styles.greenCopy}>This is a saved transaction. Inventory has been updated.</Text></View></View>
      <View style={styles.card}><Text style={styles.caption}>{data.kind === 'sale' ? 'INVOICE / TRANSACTION IDENTIFIER' : 'INTERNAL PURCHASE IDENTIFIER'}</Text><Text selectable style={styles.identifier}>{identifier}</Text>{data.kind === 'purchase' && data.invoice ? <View style={styles.row}><Text style={styles.meta}>Supplier invoice</Text><Text style={styles.bold}>{data.invoice}</Text></View> : null}<Text style={styles.meta}>{new Date(data.date).toLocaleDateString('en-IN', { dateStyle: 'medium' })} · Saved {data.kind}</Text></View>
      <View style={[styles.card, styles.contact]}><View style={styles.contactIcon}><Ionicons name={data.kind === 'sale' ? 'person-outline' : 'cube-outline'} size={22} color="#176B50" /></View><View style={{ flex: 1 }}><Text style={styles.meta}>{data.kind === 'sale' ? 'Customer' : 'Supplier'}</Text><Text style={styles.bold}>{data.contact}</Text></View></View>
      <Text style={styles.section}>{data.kind === 'sale' ? 'Items' : 'Received items'} · {data.items.length}</Text>
      {data.items.map((item) => <View key={item.id} style={styles.card}><Text style={styles.bold}>{item.name}</Text>{item.sku ? <Text style={styles.meta}>{item.sku}</Text> : null}<View style={styles.row}><Text style={[styles.meta, { flex: 1 }]}>{item.quantity} {item.label}{item.price == null ? '' : ` × ${money(item.price)}`}</Text><Text style={styles.bold}>{item.price == null ? 'Restricted' : money(Number(item.lineTotal ?? (item.quantity * item.price).toFixed(2)))}</Text></View>{item.taxAmount != null ? <View style={styles.row}><Text style={styles.meta}>GST · {Number(item.gstRate ?? 0)}%</Text><Text style={styles.bold}>{money(Number(item.taxAmount))}</Text></View> : null}{item.stockAfter !== undefined ? <Text style={styles.greenCopy}>{data.kind === 'sale' ? 'Stock remaining' : 'Stock after receipt'}: {Math.max(0, item.stockAfter).toLocaleString('en-IN', { maximumFractionDigits: 3 })} {formatUnitLabel(item.stockUnit ?? 'PIECE')}</Text> : null}</View>)}
      <View style={styles.card}>{data.subtotal != null ? <View style={styles.row}><Text style={styles.meta}>Subtotal · excluding GST</Text><Text style={styles.bold}>{money(Number(data.subtotal))}</Text></View> : null}{data.taxTotal != null ? <View style={styles.row}><Text style={styles.meta}>GST · saved item rates</Text><Text style={styles.bold}>{money(Number(data.taxTotal))}</Text></View> : null}<View style={styles.row}><Text style={styles.meta}>Total amount</Text><Text style={styles.total}>{total}</Text></View></View>
      <View style={styles.card}><Text style={styles.meta}>Payment status</Text><Text style={styles.bold}>{balance == null ? 'Payment history not confirmed' : balance === 0 ? 'Fully paid' : Number(data.amountPaid) === 0 ? 'Full credit · No payment recorded' : 'Partial payment'}</Text>{balance != null ? <><View style={styles.row}><Text style={styles.meta}>Amount {data.kind === 'sale' ? 'received' : 'paid'}</Text><Text style={styles.bold}>{money(Number(data.amountPaid))}</Text></View><View style={styles.row}><Text style={styles.meta}>{data.kind === 'sale' ? 'To collect' : 'To pay'}</Text><Text style={styles.greenTitle}>{money(balance)}</Text></View></> : null}{data.dueDate ? <View style={styles.row}><Text style={styles.meta}>Due {data.dueDate.slice(0, 10)}</Text><Text style={[styles.greenTitle, overdue && { color: '#A74737' }]}>{overdue ? 'Overdue' : balance === 0 ? 'Settled' : 'Not overdue'}</Text></View> : null}{onPayment && balance !== 0 ? <Pressable accessibilityRole="button" onPress={onPayment} style={styles.secondary}><Text style={styles.buttonText}>Record payment</Text></Pressable> : null}</View>
      {data.payments?.length ? <View style={styles.card}><Text style={styles.bold}>Payment history</Text>{data.payments.map((payment) => <View key={payment.id} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.meta}>{payment.kind === 'OPENING_BALANCE' ? 'Confirmed prior balance' : payment.method.replaceAll('_', ' ')}</Text><Text style={styles.meta}>{new Date(payment.paidAt).toLocaleDateString('en-IN')}</Text></View><Text style={styles.bold}>{money(Number(payment.amount))}</Text></View>)}</View> : null}
      {data.paymentMethod ? <View style={styles.card}><Text style={styles.meta}>Payment method</Text><Text style={styles.bold}>{data.paymentMethod.replaceAll('_', ' ')}</Text></View> : null}
      {data.note ? <View style={styles.card}><Text style={styles.meta}>Note</Text><Text style={styles.bold}>{data.note}</Text></View> : null}
      {data.items.some((item) => item.stockAfter !== undefined) ? <View style={styles.stock}><Text style={styles.greenTitle}>Stock updated for this {data.kind}</Text>{data.items.map((item) => item.stockAfter !== undefined ? <View key={item.id} style={styles.row}><Text style={[styles.meta, { flex: 1 }]}>{item.name}</Text><Text style={styles.greenTitle}>{Math.max(0, item.stockAfter).toLocaleString('en-IN', { maximumFractionDigits: 3 })} {formatUnitLabel(item.stockUnit ?? 'PIECE')}</Text></View> : null)}</View> : null}
    </ScrollView>
    <View style={[styles.footer, { paddingBottom: 12 + insets.bottom }]}><View style={styles.actions}><Pressable accessibilityRole="button" onPress={() => void share()} style={styles.secondary}><Text style={styles.buttonText}>Share receipt</Text></Pressable>{onView ? <Pressable accessibilityRole="button" onPress={onView} style={styles.secondary}><Text style={styles.buttonText}>View receipt</Text></Pressable> : onRepeat ? <Pressable accessibilityRole="button" onPress={onRepeat} style={styles.secondary}><Text style={styles.buttonText}>Repeat sale</Text></Pressable> : null}</View><Pressable accessibilityRole="button" onPress={onNew} style={styles.primary}><Text style={styles.primaryText}>Start new {data.kind}</Text></Pressable></View>
  </View>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F3F5F4' }, header: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 20, backgroundColor: '#FFFFFF' }, back: { minHeight: 44, minWidth: 32, justifyContent: 'center' }, title: { color: '#24332A', fontSize: 23, fontWeight: '800' }, content: { padding: 20, width: '100%', maxWidth: 680, alignSelf: 'center' },
  card: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E0E6E2', borderRadius: 15, padding: 16, marginBottom: 16, gap: 8 }, success: { flexDirection: 'row', gap: 10, padding: 14, borderRadius: 13, backgroundColor: '#E7F2ED', marginBottom: 16 }, greenTitle: { color: '#176B50', fontWeight: '700', fontSize: 13 }, greenCopy: { color: '#176B50', fontSize: 12, lineHeight: 18, marginTop: 4 }, meta: { color: '#737B77', fontSize: 12, lineHeight: 18 }, caption: { color: '#737B77', fontSize: 10, letterSpacing: 0.4 }, identifier: { color: '#24332A', fontSize: 22, fontWeight: '800' }, bold: { color: '#24332A', fontSize: 14, fontWeight: '700' }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, contact: { flexDirection: 'row', alignItems: 'center', gap: 12 }, contactIcon: { padding: 10, backgroundColor: '#E7F2ED', borderRadius: 10 }, section: { color: '#24332A', fontSize: 17, fontWeight: '700', marginBottom: 14 }, total: { color: '#176B50', fontSize: 25, fontWeight: '800', flexShrink: 1 }, stock: { padding: 16, borderRadius: 14, backgroundColor: '#E7F2ED', gap: 12, marginBottom: 8 }, footer: { padding: 16, backgroundColor: '#FFFFFF', borderTopWidth: 1, borderColor: '#E1E7E3', gap: 10 }, actions: { flexDirection: 'row', gap: 10 }, secondary: { flex: 1, minHeight: 48, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#DEE6E1', borderRadius: 10 }, buttonText: { color: '#176B50', fontSize: 14, fontWeight: '700' }, primary: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#176B50' }, primaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' }, error: { padding: 12, color: '#A74737' },
});
